config/routes.rb
Rails.application.routes.draw do
  post 'plays/search'
  get 'productions/list'
  resources :productions
  resources :plays
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/play.rb
class Play < ApplicationRecord
  has_many :productions
  validates :title, :playwright, :year_of_release, :male_roles, :female_roles, :total_roles, presence: true 
end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :play
  validates :theater, :zipcode, presence: true
  validates_length_of :zipcode, maximum: 5
  validates :zipcode, format: { with: /\d{5}/, message: "Zip Code should be in standard 5-digit format, eg '60652'"}
  validate :close_after_open

  def close_after_open
    if :opening > :closing
      errors.add(:closing, '-- Show cannot close before it has opened, no matter how bad it is.')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.order("title")
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  def search
    @plays = []
    Play.find_each do |p|
      if p.title.downcase.include? params[:search_string].downcase 
        @plays.push(p)
      elsif p.playwright.downcase.include? params[:search_string].downcase 
        @plays.push(p)
      end
    end
  end

  def get_prods(play)
    @prods = []
    Production.find_each do |prod|
      if prod.play_id == play.id
        @prods.push(prod)
      end
    end
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render :show, status: :created, location: @play }
      else
        format.html { render :new }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url, notice: 'Play was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:title, :playwright, :year_of_release, :male_roles, :female_roles, :total_roles, :musical, :comedy)
    end
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  before_action :set_production, only: [:show, :edit, :update, :destroy]

  # GET /productions
  # GET /productions.json
  def index
    @productions = Production.order("closing desc")
  end

  # GET /productions/1
  # GET /productions/1.json
  def show
  end

  # GET /productions/new
  def new
    @production = Production.new
  end

  # GET /productions/1/edit
  def edit
  end

  def list
    @play
  end

  # POST /productions
  # POST /productions.json
  def create
    @production = Production.new(production_params)

    respond_to do |format|
      if @production.save
        format.html { redirect_to @production, notice: 'Production was successfully created.' }
        format.json { render :show, status: :created, location: @production }
      else
        format.html { render :new }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productions/1
  # PATCH/PUT /productions/1.json
  def update
    respond_to do |format|
      if @production.update(production_params)
        format.html { redirect_to @production, notice: 'Production was successfully updated.' }
        format.json { render :show, status: :ok, location: @production }
      else
        format.html { render :edit }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productions/1
  # DELETE /productions/1.json
  def destroy
    @production.destroy
    respond_to do |format|
      format.html { redirect_to productions_url, notice: 'Production was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_production
      @production = Production.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def production_params
      params.require(:production).permit(:play_id, :theater, :zipcode, :opening, :closing, :production_notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayAround</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="headcard">
      <a href="/plays/">Plays</a>
      <img src="/drama_masks.png" height="60px">
      <a href="/productions/">Productions</a>
      <span id="search_bar">
        <%= form_tag "/plays/search" do %>
          <%= text_field_tag :search_string %>
          <%= submit_tag "Search" %>
        <% end %>
      </span>
      
    </div>
    
    <div id="padding"></div>
    <p style="color: blue"><%= flash[:notice] %></p>
    </br>
    <div id="content">
    <%= yield %>
    </div>
  </body>
</html>

app/views/plays/_form.html.erb
<%= form_with(model: play, local: true) do |form| %>
  <% if play.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(play.errors.count, "error") %> prohibited this play from being saved:</h2>

      <ul>
      <% play.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :play_title %>
  </div>

  <div class="field">
    <%= form.label :playwright %>
    <%= form.text_field :playwright, id: :play_playwright %>
  </div>

  <div class="field">
    <%= form.label :year_of_release %>
    <%= form.text_field :year_of_release, id: :play_year_of_release %>
  </div>

  <div class="field">
    <%= form.label :male_roles %>
    <%= form.number_field :male_roles, id: :play_male_roles %>
  </div>

  <div class="field">
    <%= form.label :female_roles %>
    <%= form.number_field :female_roles, id: :play_female_roles %>
  </div>

  <div class="field">
    <%= form.label :total_roles %>
    <%= form.number_field :total_roles, id: :play_total_roles %>
  </div>

  <div class="field">
    <%= form.label :musical %>
    <%= form.check_box :musical, id: :play_musical %>
  </div>

  <div class="field">
    <%= form.label :comedy %>
    <%= form.check_box :comedy, id: :play_comedy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plays/_new_production.html.erb
<%= form_with(model: production, local: true) do |form| %>
  <% if production.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(production.errors.count, "error") %> prohibited this production from being saved:</h2>

      <ul>
      <% production.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= form.hidden_field :play_id %>
  </div>

  <div class="field">
    <%= form.label :theater %>
    <%= form.text_field :theater, id: :production_theater %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: :production_zipcode %>
  </div>

  <div class="field">
    <%= form.label :opening %>
    <%= form.date_select :opening, id: :production_opening %>
  </div>

  <div class="field">
    <%= form.label :closing %>
    <%= form.date_select :closing, id: :production_closing %>
  </div>

  <div class="field">
    <%= form.label :production_notes %>
    <%= form.text_area :production_notes, id: :production_production_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plays/_prod_list.erb
<p id="notice"><%= notice %></p>
</br>
<h2>Productions</h2>

<table>
  <thead>
    <tr>
      <th>Theater</th>
      <th>Zip code</th>
      <th>Year</th>
      <th>Production notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% productions.each do |production| %>
      <tr>
        <td><%= production.theater %></td>
        <td><%= production.zipcode %></td>
        <td><%= production.closing.year %></td>
        <td><%= production.production_notes %></td>
        <td><%= link_to 'Show', production %></td>
        <td><%= link_to 'Edit', edit_production_path(production) %></td>
        <td><%= link_to 'Destroy', production, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plays/edit.html.erb
<h1>Editing Play</h1>

<%= render 'form', play: @play %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

app/views/plays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plays</h1>

<table>
  <thead>
    <tr>
      <th>Title  </th>
      <th>Playwright  </th>
      <th>Year of Release  </th>
      <th>Males  </th>
      <th>Females  </th>
      <th>Total Roles  </th>
      <th>Musical  </th>
      <th>Comedy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="middle">
    <% @plays.each do |play| %>
      <tr>
        <td><%= link_to play.title, play %></td>
        <td><%= play.playwright %></td>
        <td><%= play.year_of_release %></td>
        <td><%= play.male_roles %></td>
        <td><%= play.female_roles %></td>
        <td><%= play.total_roles %></td>
        <td><%= play.musical %></td>
        <td><%= play.comedy %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
        <td><%= link_to 'Destroy', play, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Play', new_play_path %>

app/views/plays/new.html.erb
<h1>New Play</h1>

<%= render 'form', play: @play %>

<%= link_to 'Back', plays_path %>

app/views/plays/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Results for: <%= params[:search_string] %></h1>

<table>
  <thead>
    <tr>
      <th>Title  </th>
      <th>Playwright  </th>
      <th>Year of Release  </th>
      <th>Males  </th>
      <th>Females  </th>
      <th>Total Roles  </th>
      <th>Musical  </th>
      <th>Comedy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="middle">
    <% @plays.each do |play| %>
      <tr>
        <td><%= link_to play.title, play %></td>
        <td><%= play.playwright %></td>
        <td><%= play.year_of_release %></td>
        <td><%= play.male_roles %></td>
        <td><%= play.female_roles %></td>
        <td><%= play.total_roles %></td>
        <td><%= play.musical %></td>
        <td><%= play.comedy %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Play', new_play_path %>

app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>
</br>
<p>
  <h2>
  <%= @play.title %>
  </h2>
</p>

<p>
  <strong>Playwright:</strong>
  <%= @play.playwright %>
</p>

<p>
  <strong>Year of Release:</strong>
  <%= @play.year_of_release %>
</p>

<p>
  <strong>Male Roles:</strong>
  <%= @play.male_roles %>
</p>

<p>
  <strong>Female Roles:</strong>
  <%= @play.female_roles %>
</p>

<p>
  <strong>Total Roles:</strong>
  <%= @play.total_roles %>
</p>

<p>
  <strong>Musical:</strong>
  <% if @play.musical %>
    Yes
  <% else %>
    No
  <% end %>
</p>

<p>
  <strong>Comedy:</strong>
  <% if @play.comedy %>
    Yes
  <% else %>
    No
  <% end %>
</p>

<%= link_to 'Edit', edit_play_path(@play) %> |
<%= link_to 'Back', plays_path %>
</br>

<div id=list_prods>
  <%= render :partial=>"prod_list", :locals=>{:productions=>Production.where(play_id: @play.id)} %>
</div>


<h2>Add a new Production of this show:</h2>

<%= render :partial=>"new_production", :locals=>{:production=>Production.new(:play_id=>@play.id)} %>

app/views/productions/_form.html.erb
<%= form_with(model: production, local: true) do |form| %>
  <% if production.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(production.errors.count, "error") %> prohibited this production from being saved:</h2>

      <ul>
      <% production.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= @production.play.title</h2>
  </div>

  <div class="field">
    <%= form.label :theater %>
    <%= form.text_field :theater, id: :production_theater %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: :production_zipcode %>
  </div>

  <div class="field">
    <%= form.label :opening %>
    <%= form.date_select :opening, id: :production_opening %>
  </div>

  <div class="field">
    <%= form.label :closing %>
    <%= form.date_select :closing, id: :production_closing %>
  </div>

  <div class="field">
    <%= form.label :production_notes %>
    <%= form.text_area :production_notes, id: :production_production_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productions/_new_form.html.erb
<%= form_with(model: production, local: true) do |form| %>
  <% if production.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(production.errors.count, "error") %> prohibited this production from being saved:</h2>

      <ul>
      <% production.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :play_name %>
    <%= form.text_field :play_name, id: :production_play_name %>
  </div>

  <div class="field">
    <%= form.label :theater %>
    <%= form.text_field :theater, id: :production_theater %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.number_field :zip_code, id: :production_zip_code %>
  </div>

  <div class="field">
    <%= form.label :opening %>
    <%= form.date_select :opening, id: :production_opening %>
  </div>

  <div class="field">
    <%= form.label :closing %>
    <%= form.date_select :closing, id: :production_closing %>
  </div>

  <div class="field">
    <%= form.label :production_notes %>
    <%= form.text_area :production_notes, id: :production_production_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productions/edit.html.erb
<h1>Editing Production</h1>

<%= render 'form', production: @production %>

<%= link_to 'Show', @production %> |
<%= link_to 'Back', productions_path %>

app/views/productions/index.html.erb
<p id="notice"><%= notice %></p>
</br>
<h1>Productions</h1>

<table>
  <thead>
    <tr>
      <th>Play</th>
      <th>Theater</th>
      <th>Zip code</th>
      <th>Year</th>
      <th>Production notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productions.each do |production| %>
      <tr>
        <td><%= production.play.title %></td>
        <td><%= production.theater %></td>
        <td><%= production.zipcode %></td>
        <td><%= production.closing.year %></td>
        <td><%= production.production_notes %></td>
        <td><%= link_to 'Show', production %></td>
        <td><%= link_to 'Edit', edit_production_path(production) %></td>
        <td><%= link_to 'Destroy', production, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/productions/new.html.erb
<h1>New Production</h1>

<%= render 'new_form', production: @production %>

<%= link_to 'Back', productions_path %>

app/views/productions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Play:</strong>
  <%= @production.play.title %>
</p>

<p>
  <strong>Theater:</strong>
  <%= @production.theater %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @production.zipcode %>
</p>

<p>
  <strong>Opening:</strong>
  <%= @production.opening %>
</p>

<p>
  <strong>Closing:</strong>
  <%= @production.closing %>
</p>

<p>
  <strong>Production notes:</strong>
  <%= @production.production_notes %>
</p>

<%= link_to 'Edit', edit_production_path(@production) %> |
<%= link_to 'Back', productions_path %>